name: K6 Extension Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 counter extension run
    runs-on: ubuntu-latest
    container: docker://golang:1.17-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest



      - name: Build xk6-counter binary
        run: xk6 build --with github.com/mstoykov/xk6-counter@latest

#      - name: Build xk6-mongo binary
#        run: xk6 build --with github.com/GhMartingit/xk6-mongo

